### ISSUE TITLE
Allow Country Codes for Languages

### ISSUE THREAD

**Issue by devinmatte** [devinmatte/wasp#15]
Allow for country codes like `en-us`, listed [here](https://www.andiamo.co.uk/resources/iso-language-codes). 
More details after #14 Merged

**Comment by saifat29** [comment]
@devinmatte I'd like to work on this however I have a suggestion.
We use hardcoded list of valid language codes to check the user input against it, this makes the code very long.

I recently came across a python module called [pycountry](https://pypi.python.org/pypi/pycountry)
which will make our code very short. But then we'll have to make a setup.py file so that the user can install the dependencies. 

What do you suggest?

**Comment by devinmatte** [comment]
@saifat29 So I'd prefer to not have a hardcoded list, however I also don't want to expand this to too many dependencies. 
If you can get it working, with pycountry and the `setup.py` with debian packaging still working (You can test using the command from the README, or push and ask me to test if you're not on a debian based distro) then I'd be on board.
I do want to make sure we can still package it properly even with dependencies.

**Comment by saifat29** [comment]
@devinmatte I don't know how debian packaging work. But I am sure the code will work with pycountry. 
Also there is no setup.py currently in the repository. And since I am very new to Python I don't have an idea how installation of dependencies through `setup.py` and debian packaging will go together.

**Comment by devinmatte** [comment]
@saifat29 So I'm only familiar with the basics of both `setup.py` and debian packaging. 
I can do some research and help you out with it. Feel free to put in a pull request for using pycountry and as much as you can figure out. 

I'll look into the packaging portion of it

**Comment by saifat29** [comment]
Ok cool, I'll get started with it. 👍

**Comment by saifat29** [comment]
@devinmatte While going through the documentation I came to know that pycountry provides ISO language code and country code separately, so to generate codes like `en-us` we'll have to map language and country codes by parsing the XML file that pycountry refers to, which in turn will require to install other dependencies. 
I think for now we'll have to manually hardcode the list of codes.
Refer this [SO link](https://stackoverflow.com/questions/2680619/match-language-code-with-countries-where-this-language-is-an-official-or-commonl) for more info.

**Comment by devinmatte** [comment]
I want to get this done soon:tm: so that I can close out v1.0

@saifat29 Are you going to tackle this still (even if we're hardcoding them) or should I open this up for other people?

**Comment by saifat29** [comment]
I'll do it and submit PR ASAP.
