### ISSUE TITLE
Color Validation

### ISSUE THREAD

**Issue by devinmatte** [devinmatte/wasp#8]
Find a way to validate color strings. I'm fine with limiting it to hex values during the first version if that's what it takes to get proper validation.

```python
def theme_color(self):
    # TODO: Default
    # TODO: Validation
    self.details['theme_color'] = input("Theme Color " + str(on(["M"], args)) + ": ")

def background_color(self):
    # TODO: Default
    # TODO: Validation
    self.details['background_color'] = input("Background Color " + str(on(["M"], args)) + ": ")
```

**Comment by tuantr10** [comment]
Hi @devinmatte , may I work on this? I have never contributed to any other repositories rather than my own. 
For the flow: I will limit the input value to 6-digits-length hex values. 
I have 2 questions:
- Should we also allow hex values with the length of 3?
- Will empty input work with these 2 fields (theme_color, background_color)?

**Comment by devinmatte** [comment]
@tuantr10 Absolutely! I would love for someone to contribute. 
Limiting to 6 values is perfect. If you want to allow 3 digit hexes that's fine, but I don't feel it required.
As for allowing empty input, look at the other methods that accept empty input, and set a default. I think #FFF should be the default value.

**Comment by tuantr10** [comment]
Thanks @devinmatte. I will create a PR when I finish.

**Comment by tuantr10** [comment]
@devinmatte please check and feedback my above pull request.
Cheers!
